pipeline {
 agent any

 stages {

  stage("Build Images") {
   steps {
    sh "docker build -t product-service services/product-service"
    sh "docker build -t catalog-service services/catalog-service"
    sh "docker build -t cart-service services/cart-service"
    sh "docker build -t payment-service services/payment-service"
   }
  }

  stage("Deploy to K8s") {
   steps {
    sh "kubectl apply -f k8s/"
   }
  }
 }
}
